work_dict = {
    "workLoadName": "None",
    "backupType": "vm",
    "site": "Site_A",
    "workLoadCap": 0,
    "growthPercent": 10,
    "scopeYears": 5,
    "backupWindow": 8,
    "changeRate": 5,
    "reduction": 50,
    "vmQty": 0,
    "vmVmdkRatio": 4,
    "usePerVM": "perVM",
    "useReFs": "yes",
    "rpsBu": 30,
    "cloudMove": 0,
    "buWeekly": 0,
    "buMonthly": 12,
    "buYearly": 0,
    "copySite": "Site_B",
    "rpsBuCopy": 30,
    "buCopyWeekly": 0,
    "buCopyMonthly": 0,
    "buCopyYearly": 0,
    "cloudEnabled": "false",
    "bandWidthInc": 0,
    "vmdkQty": 0,
}
